//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaJOIN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UsuarioXCiudad
    {
        public int Id { get; set; }
        public int IdUser { get; set; }
        public int IdCiudad { get; set; }
        public string Obervaciones { get; set; }
    
        public virtual Ciudad Ciudad { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
